/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'school' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'targetClass' : IDL.Text,
});
export const ContextExample = IDL.Record({
  'id' : IDL.Nat,
  'exampleText' : IDL.Text,
  'school' : IDL.Text,
  'targetClass' : IDL.Text,
});
export const FeedbackEntry = IDL.Record({
  'id' : IDL.Nat,
  'pedagogicalAlignment' : IDL.Nat,
  'additionalComments' : IDL.Text,
  'school' : IDL.Text,
  'knowledgeTransfer' : IDL.Nat,
  'timestamp' : IDL.Int,
  'sensoryExperience' : IDL.Nat,
  'environmentalContribution' : IDL.Text,
  'impactMoment' : IDL.Text,
  'targetClass' : IDL.Text,
  'interactionMethod' : IDL.Nat,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContextStats = IDL.Record({
  'averageInteractionMethod' : IDL.Float64,
  'totalEntries' : IDL.Nat,
  'averagePedagogicalAlignment' : IDL.Float64,
  'averageKnowledgeTransfer' : IDL.Float64,
  'averageSensoryExperience' : IDL.Float64,
});
export const Timestamp = IDL.Int;
export const Score = IDL.Nat;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addActivity' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addContextExample' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addQuestion' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
  'adminLogout' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changeAdminPassword' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'deleteActivity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteContextExample' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteQuestion' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getActivitiesBySchoolAndClass' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Activity)],
      ['query'],
    ),
  'getActivityById' : IDL.Func([IDL.Nat], [IDL.Opt(Activity)], ['query']),
  'getAllActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getAllContextExamples' : IDL.Func([], [IDL.Vec(ContextExample)], ['query']),
  'getAllFeedback' : IDL.Func([IDL.Text], [IDL.Vec(FeedbackEntry)], ['query']),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryStatsBySchool' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ContextStats)],
      ['query'],
    ),
  'getContextExampleById' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ContextExample)],
      ['query'],
    ),
  'getContextExamplesBySchoolAndClass' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(ContextExample)],
      ['query'],
    ),
  'getFeedbackByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FeedbackEntry)],
      ['query'],
    ),
  'getFeedbackByClass' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(FeedbackEntry)],
      ['query'],
    ),
  'getFeedbackByDateRange' : IDL.Func(
      [Timestamp, Timestamp],
      [IDL.Vec(FeedbackEntry)],
      ['query'],
    ),
  'getFeedbackBySchool' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FeedbackEntry)],
      ['query'],
    ),
  'getFeedbackByScoreRange' : IDL.Func(
      [Score, Score],
      [IDL.Vec(FeedbackEntry)],
      ['query'],
    ),
  'getQuestionById' : IDL.Func([IDL.Nat], [IDL.Opt(Question)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSessionValid' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedInitialData' : IDL.Func([IDL.Text], [], []),
  'submitFeedback' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Score,
        Score,
        Score,
        Score,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateActivity' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateContextExample' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateQuestion' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'school' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'targetClass' : IDL.Text,
  });
  const ContextExample = IDL.Record({
    'id' : IDL.Nat,
    'exampleText' : IDL.Text,
    'school' : IDL.Text,
    'targetClass' : IDL.Text,
  });
  const FeedbackEntry = IDL.Record({
    'id' : IDL.Nat,
    'pedagogicalAlignment' : IDL.Nat,
    'additionalComments' : IDL.Text,
    'school' : IDL.Text,
    'knowledgeTransfer' : IDL.Nat,
    'timestamp' : IDL.Int,
    'sensoryExperience' : IDL.Nat,
    'environmentalContribution' : IDL.Text,
    'impactMoment' : IDL.Text,
    'targetClass' : IDL.Text,
    'interactionMethod' : IDL.Nat,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContextStats = IDL.Record({
    'averageInteractionMethod' : IDL.Float64,
    'totalEntries' : IDL.Nat,
    'averagePedagogicalAlignment' : IDL.Float64,
    'averageKnowledgeTransfer' : IDL.Float64,
    'averageSensoryExperience' : IDL.Float64,
  });
  const Timestamp = IDL.Int;
  const Score = IDL.Nat;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addActivity' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addContextExample' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addQuestion' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
    'adminLogout' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changeAdminPassword' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'deleteActivity' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteContextExample' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteQuestion' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getActivitiesBySchoolAndClass' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Activity)],
        ['query'],
      ),
    'getActivityById' : IDL.Func([IDL.Nat], [IDL.Opt(Activity)], ['query']),
    'getAllActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getAllContextExamples' : IDL.Func(
        [],
        [IDL.Vec(ContextExample)],
        ['query'],
      ),
    'getAllFeedback' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FeedbackEntry)],
        ['query'],
      ),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryStatsBySchool' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ContextStats)],
        ['query'],
      ),
    'getContextExampleById' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ContextExample)],
        ['query'],
      ),
    'getContextExamplesBySchoolAndClass' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(ContextExample)],
        ['query'],
      ),
    'getFeedbackByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FeedbackEntry)],
        ['query'],
      ),
    'getFeedbackByClass' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(FeedbackEntry)],
        ['query'],
      ),
    'getFeedbackByDateRange' : IDL.Func(
        [Timestamp, Timestamp],
        [IDL.Vec(FeedbackEntry)],
        ['query'],
      ),
    'getFeedbackBySchool' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FeedbackEntry)],
        ['query'],
      ),
    'getFeedbackByScoreRange' : IDL.Func(
        [Score, Score],
        [IDL.Vec(FeedbackEntry)],
        ['query'],
      ),
    'getQuestionById' : IDL.Func([IDL.Nat], [IDL.Opt(Question)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSessionValid' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedInitialData' : IDL.Func([IDL.Text], [], []),
    'submitFeedback' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Score,
          Score,
          Score,
          Score,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateActivity' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateContextExample' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateQuestion' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };