/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : bigint,
  'school' : string,
  'name' : string,
  'description' : string,
  'targetClass' : string,
}
export interface ContextExample {
  'id' : bigint,
  'exampleText' : string,
  'school' : string,
  'targetClass' : string,
}
export interface ContextStats {
  'averageInteractionMethod' : number,
  'totalEntries' : bigint,
  'averagePedagogicalAlignment' : number,
  'averageKnowledgeTransfer' : number,
  'averageSensoryExperience' : number,
}
export interface FeedbackEntry {
  'id' : bigint,
  'pedagogicalAlignment' : bigint,
  'additionalComments' : string,
  'school' : string,
  'knowledgeTransfer' : bigint,
  'timestamp' : bigint,
  'sensoryExperience' : bigint,
  'environmentalContribution' : string,
  'impactMoment' : string,
  'targetClass' : string,
  'interactionMethod' : bigint,
}
export interface Question {
  'id' : bigint,
  'title' : string,
  'description' : string,
}
export type Score = bigint;
export type Timestamp = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addActivity' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'addContextExample' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'addQuestion' : ActorMethod<[string, string, string], undefined>,
  'adminLogin' : ActorMethod<[string, string], [] | [string]>,
  'adminLogout' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changeAdminPassword' : ActorMethod<[string, string, string], boolean>,
  'deleteActivity' : ActorMethod<[string, bigint], undefined>,
  'deleteContextExample' : ActorMethod<[string, bigint], undefined>,
  'deleteQuestion' : ActorMethod<[string, bigint], undefined>,
  'getActivitiesBySchoolAndClass' : ActorMethod<
    [string, string],
    Array<Activity>
  >,
  'getActivityById' : ActorMethod<[bigint], [] | [Activity]>,
  'getAllActivities' : ActorMethod<[], Array<Activity>>,
  'getAllContextExamples' : ActorMethod<[], Array<ContextExample>>,
  'getAllFeedback' : ActorMethod<[string], Array<FeedbackEntry>>,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryStatsBySchool' : ActorMethod<[string], [] | [ContextStats]>,
  'getContextExampleById' : ActorMethod<[bigint], [] | [ContextExample]>,
  'getContextExamplesBySchoolAndClass' : ActorMethod<
    [string, string],
    Array<ContextExample>
  >,
  'getFeedbackByCategory' : ActorMethod<[string], Array<FeedbackEntry>>,
  'getFeedbackByClass' : ActorMethod<[string, string], Array<FeedbackEntry>>,
  'getFeedbackByDateRange' : ActorMethod<
    [Timestamp, Timestamp],
    Array<FeedbackEntry>
  >,
  'getFeedbackBySchool' : ActorMethod<[string], Array<FeedbackEntry>>,
  'getFeedbackByScoreRange' : ActorMethod<[Score, Score], Array<FeedbackEntry>>,
  'getQuestionById' : ActorMethod<[bigint], [] | [Question]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSessionValid' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedInitialData' : ActorMethod<[string], undefined>,
  'submitFeedback' : ActorMethod<
    [string, string, Score, Score, Score, Score, string, string, string],
    undefined
  >,
  'updateActivity' : ActorMethod<
    [string, bigint, string, string, string, string],
    undefined
  >,
  'updateContextExample' : ActorMethod<
    [string, bigint, string, string, string],
    undefined
  >,
  'updateQuestion' : ActorMethod<[string, bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];